#!/bin/sh

command -v nodejs
if [ $? -eq 0 ]; then
    NODEJS=nodejs
else
    NODEJS=node
fi

if [ -f usr/share/schoollibrary/server.js ]
then
    $NODEJS usr/share/schoollibrary/server.js
else
    $NODEJS /usr/share/schoollibrary/server.js
fi
